//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Businesses
    {
        public int businessId { get; set; }
        public string businessName { get; set; }
        public string businessDescription { get; set; }
    }
}
