//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int projectId { get; set; }
        public string projectName { get; set; }
        public string projectDescription { get; set; }
        public int mediaId { get; set; }
    
        public virtual Media Media { get; set; }
    }
}
