//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string customerLastName { get; set; }
        public string customerMail { get; set; }
        public string customerPhoneNumber { get; set; }
        public string customerMessage { get; set; }
    }
}
